# Site settings
title: OmniOS Community Edition
description: illumos based server OS with ZFS, KVM and Linux zone support
url: "http://www.omniosce.org"
baseurl: ""
logo: OmniOS Community Edition
paginate: 5
paginate_path: "/page:num/"
owner:
    email: info@omniosce.org
    facebook:
        show: true
        name: "OmniOS Commuity Editoin"
        url: "https://fb.me/omniosce"
    github:
        show: true
        username: "omniosorg"
    twitter:
        show: true
        username: "omniosce"
    disqus:
        show: false
        username: "ichihararifa"
    linkedin:
        show: false
        profile: "https://linkedin.com/in/your-profile-id-here"
sass:
    sass_dir: _sass
    style: compressed
permalink: "/article/:title"
highlighter: pygments
gems:
    - jekyll-feed
