# Permalinks
#
permalink:           pretty

# Setup
title:               'OmniOS Community Edition'
tagline:             'illumos based server OS with ZFS, KVM and Linux zone support'
description:         'Description ... '
url:                 http://omniosce.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              OmniOS Community Edition Association
  url:               http://omniosce.org
  email:             info@omniosce.org

# Custom vars
version:             1.0.0
