# Site settings
title: OmniOS Community Edition
description: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
url: "http://www.omniosce.org"
baseurl: ""
logo: OmniOS Community Edition
paginate: 5
paginate_path: "/page:num/"
owner:
    email: info@omniosce.org
    facebook:
        show: true
        name: "OmniOS Commuity Editoin"
        url: "https://fb.me/omniosce"
    github:
        show: true
        username: "omniosorg"
    twitter:
        show: true
        username: "omniosce"
    disqus:
        show: false
        username: "ichihararifa"
    linkedin:
        show: false
        profile: "https://linkedin.com/in/your-profile-id-here"
sass:
    sass_dir: _sass
    style: compressed
permalink: "/article/:title"
highlighter: pygments
gems:
    - jekyll-feed
